### ISSUE TITLE
Add LIVE badge when event's Twitch stream is live

### ISSUE THREAD

**Issue by sebj** [sebj/r-CompetitiveOverwatch-Bot#3]
https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#get-streamschannel

`GET /streams/:channel/` returns a stream object if live.

**Comment by ghost** [comment]
If you plan to implement this by checking if a twitch stream is live you might have trouble with some always-live channels, like ESL who stream rebroadcasts 24/7

**Comment by sebj** [comment]
True, although I might just take a "cross that bridge when we come to it" approach, seeing as most other tourneys should be ok. Could always check whether stream title has "Rebroadcast" in it actually.
